### ISSUE TITLE
Clarify "Push notifications"

### ISSUE THREAD

**Issue by UserNaem** [lewd-site/TinyIB#100]
"May not work if onesignal.com is blocked" fails to state (or even imply) what exactly does it apply to - just the browser notifications, or the entire notifications section, or the entire Posts tab. This can be rephrased to "Browser notifications will not work if onesignal.com is blocked or down"; there's no room for a "may" here, they absolutely will not work if onesignal.com is unavailable for any reason.
Also, do these work after the browser tab is closed? If not, they shouldn't be called "push" notifications, as push notifications are designed for background applications on certain OSes.
![image](https://user-images.githubusercontent.com/21028464/66301574-d099ce00-e910-11e9-8521-8ee01e49a346.png)

**Comment by VVatashi** [comment]
Yes, this is actually push notifications.
Desktop notifications (that are not dependent on external services, but only work when the tab is open) are planned later.
