### ISSUE TITLE
Fix user password edit not working in the admin panel

### ISSUE THREAD

**Issue by VVatashi** [lewd-site/TinyIB#90]
Steps to reproduce:
- Login as administrator/moderator.
- Go to the admin/users page, click edit button for any user.
- Enter new password, submit form.

Expected: this user can login with the new password now.
Probably not working for some reason.

**Comment by techiedesu** [comment]
@VVatashi login form looks broken.

![image](https://user-images.githubusercontent.com/21150432/65391098-62d99800-dd8f-11e9-99d1-ed51dd93e5c5.png)

**Comment by techiedesu** [comment]
Oops. First symbol is space.
