### ISSUE TITLE
Multi-line quotes are (still) broken

### ISSUE THREAD

**Issue by UserNaem** [lewd-site/TinyIB#96]
STR:
Select multiple lines of text and press the quote button
Expected result:
Selected text is inserted and "> " is prepended to each line
Actual result:
Works mostly as it should, but the text cursor stays on the last line of the multi-line quote instead of moving down to the empty line below.

Trying to insert a multi-line quote in the middle of a message gets even worse, the text cursor is moved inconsistently and ends up where it absolutely shouldn't be. Here's a demonstration:
https://files.catbox.moe/sypnly.mp4
https://files.catbox.moe/bh5mtp.mp4

**Comment by techiedesu** [comment]
Reproduced on Windows-based host only.
